n = int(input("enter a number: "))
name = input("Name: ")
print(f"Name is {name}")
print(str(n), "+", str(2), "=", str(n+2))
print(str(n), "-", str(2), "=", str(n-2))
print(str(n), "*", str(2), "=", str(n*2))
print(str(n), "/", str(2), "=", str(n/2))
print(str(n), "//", str(2), "=", str(n//2))
print(str(n), "%", str(2), "=", str(n%2))
print(str(n), "**", str(2), "=", str(n**2))
